# Makefile for LaTeX Thesis Template
# Defines a 'clean' command to remove auxiliary files from all subdirectories.

# The .PHONY rule tells 'make' that 'clean' is a command, not a file.
.PHONY: clean

clean:
	@echo "🧹 Cleaning up LaTeX auxiliary files from all subdirectories..."
	
	# Use 'find' to locate and delete temporary files in the current directory and all subdirectories.
	# The backslashes (\) are just for formatting to make the long list of file extensions readable.
	find . -type f \( \
        -name "*.aux" -o \
        -name "*.bcf" -o \
        -name "*.out" -o \
        -name "*.bbl" -o \
        -name "*.blg" -o \
        -name "*.brf" -o \
        -name "*.idx" -o \
        -name "*.ind" -o \
        -name "*.ilg" -o \
        -name "*.lof" -o \
        -name "*.lot" -o \
        -name "*.log" -o \
        -name "*.fls" -o \
        -name "*.fdb_latexmk" -o \
        -name "*.synctex.gz" -o \
        -name "*.toc" -o \
        -name "*.xml" -o \
        -name "*.latexmkrc" -o \
        -name "*.nav" -o \
        -name "*.snm" \
	\) -delete
	
	# Remove the cache directory generated by the 'minted' package
	rm -rf _minted-*/
	
	@echo "✅ Cleanup complete!"